services:
  gateway:
    build: ./gateway
    container_name: dms-gateway
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      USER_AUTH_URL: http://auth-service:3001
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch index.js
    depends_on:
      auth-service:
        condition: service_started
      document-service:
        condition: service_started
      user-service:
        condition: service_started
      notification-service:
        condition: service_started

  auth-service:
    build: ./services/auth-service
    container_name: dms-auth
    ports:
      - "3001:3001"
    env_file: ./.env
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch user-auth.js

  document-service:
    build: ./services/document-service
    container_name: dms-document
    ports:
      - "3002:3002"
    env_file: ./.env
    volumes:
      - ./services/document-service:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch index.js

  user-service:
    build: ./services/user-service
    container_name: dms-user
    ports:
      - "3003:3003"
    env_file: ./.env
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch index.js

  notification-service:
    build: ./services/notification-service
    container_name: dms-notification
    ports:
      - "3004:3004"
    env_file: ./.env
    volumes:
      - ./services/notification-service:/app
      - /app/node_modules
    command: npx nodemon --legacy-watch index.js
